"""Initial Migration

Revision ID: 3a978a39f7c1
Revises: 3676beff361b
Create Date: 2021-08-18 10:27:43.969331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a978a39f7c1'
down_revision = '3676beff361b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'posted')
    # ### end Alembic commands ###
