"""Initial Migration

Revision ID: 690bed541772
Revises: 29b3b3dc5a66
Create Date: 2021-08-17 16:15:02.990657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690bed541772'
down_revision = '29b3b3dc5a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
