"""Initial Migration

Revision ID: 737b6c838e7e
Revises: e8407c98af6b
Create Date: 2021-08-18 23:49:50.821992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737b6c838e7e'
down_revision = 'e8407c98af6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_category_fkey', 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitch_category_fkey', 'pitch', 'categories', ['category'], ['id'])
    op.drop_column('pitch', 'category_id')
    # ### end Alembic commands ###
