"""Initial Migration

Revision ID: d42981c82317
Revises: 737b6c838e7e
Create Date: 2021-08-20 00:04:30.821344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42981c82317'
down_revision = '737b6c838e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_name')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_table('table_name',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('some_column', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('another_column', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_name_pkey')
    )
    # ### end Alembic commands ###
