"""Initial Migration

Revision ID: e8407c98af6b
Revises: 36e2ac0ca627
Create Date: 2021-08-18 16:50:04.427625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8407c98af6b'
down_revision = '36e2ac0ca627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pitch', 'users', ['owner'], ['id'])
    op.create_foreign_key(None, 'pitch', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    # ### end Alembic commands ###
