"""Initial Migration

Revision ID: ed933fc7d088
Revises: d42981c82317
Create Date: 2021-08-23 12:33:24.299444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed933fc7d088'
down_revision = 'd42981c82317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'downvotes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'downvotes', 'pitch', ['pitch_id'], ['id'])
    op.create_foreign_key(None, 'upvotes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'upvotes', 'pitch', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    # ### end Alembic commands ###
